CREATE TABLE IF NOT EXISTS sesiones_pos (
  id INTEGER PRIMARY KEY,
  administrador_id INTEGER NOT NULL REFERENCES empleados(id),
  abierta_en TEXT NOT NULL,
  cerrada_en TEXT
);

ALTER TABLE mesas ADD COLUMN pos_x REAL NOT NULL DEFAULT 40;
ALTER TABLE mesas ADD COLUMN pos_y REAL NOT NULL DEFAULT 40;
ALTER TABLE mesas ADD COLUMN forma TEXT NOT NULL DEFAULT 'square';
ALTER TABLE mesas ADD COLUMN ancho REAL NOT NULL DEFAULT 88;
ALTER TABLE mesas ADD COLUMN alto REAL NOT NULL DEFAULT 88;
