ALTER TABLE pisos ADD COLUMN fondo_color TEXT;
ALTER TABLE pisos ADD COLUMN activo INTEGER NOT NULL DEFAULT 1;
ALTER TABLE mesas ADD COLUMN fondo_color TEXT;
ALTER TABLE mesas ADD COLUMN fondo_data TEXT;
